# Generated by Django 5.2.4 on 2025-07-31 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_received_quantity_inwarditem_quantity'),
        ('loading', '0002_loading_loaded_at_loading_loaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='loading',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
