# Generated by Django 5.2.4 on 2025-07-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventoryprocesstype_remove_inventorylog_action_type_and_more'),
        ('loading', '0003_loading_item_loading_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='outward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventorytransaction'),
        ),
    ]
