# Generated by Django 5.2.4 on 2025-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_created_by_inventory_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outward',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outward',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
