# Generated by Django 5.2.4 on 2025-07-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryactiontype_itembatch_itemcategory_itemlot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='unit_price',
            new_name='rate',
        ),
    ]
