# Generated by Django 5.2.4 on 2025-07-29 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_unit_price_purchaseorderitem_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outward',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outward',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
