# Generated by Django 5.2.4 on 2025-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_outward_created_by_outward_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreturn',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
