# Generated by Django 5.2.4 on 2025-07-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryreturn_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreturn',
            old_name='remark',
            new_name='remarks',
        ),
    ]
