# Generated by Django 5.2.4 on 2025-07-30 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inwarditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inwarditem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inwarditem',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='inwarditem',
            name='remarks',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
