# Generated by Django 5.2.4 on 2025-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inwarditem_created_at_inwarditem_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
