# Generated by Django 5.2.4 on 2025-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inward_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
