# Generated by Django 5.2.4 on 2025-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inward_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwarditem',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inwarditem',
            name='received_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
