# Generated by Django 5.2.4 on 2025-07-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inwarditem_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwarditem',
            old_name='received_quantity',
            new_name='quantity',
        ),
    ]
