# Generated by Django 5.2.4 on 2025-07-31 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_customer_item_barcode_notification_salesorder'),
        ('warehouse', '0004_location_address_line1_location_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventoryreturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryreturn',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryreturn',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='purchase_order_item',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inwarditem',
            name='inward',
        ),
        migrations.RemoveField(
            model_name='inwarditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inwarditem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='inwarditem',
            name='purchase_order_item',
        ),
        migrations.RemoveField(
            model_name='inwarditem',
            name='quality_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='dispatched_by',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='item',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='location',
        ),
        migrations.RemoveField(
            model_name='outward',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_changed_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_reference_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_rating', models.FloatField(blank=True, null=True)),
                ('is_dispatched', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_defective', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispatches', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_from', to='warehouse.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.location')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryprocesstype')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.supplier')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_to', to='warehouse.location')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salesorder')),
            ],
        ),
        migrations.DeleteModel(
            name='CycleCount',
        ),
        migrations.DeleteModel(
            name='InventoryActionType',
        ),
        migrations.DeleteModel(
            name='InventoryAdjustment',
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
        migrations.DeleteModel(
            name='InventoryReturn',
        ),
        migrations.DeleteModel(
            name='InventoryTransfer',
        ),
    ]
