# Generated by Django 5.2.4 on 2025-07-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventoryprocesstype_remove_inventorylog_action_type_and_more'),
        ('loading', '0004_alter_loading_outward'),
        ('tasks', '0003_remove_putawaytask_assigned_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inward',
        ),
        migrations.DeleteModel(
            name='InwardItem',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Outward',
        ),
    ]
