# Generated by Django 5.2.4 on 2025-07-28 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_created_by_inventory_updated_by_and_more'),
        ('tasks', '0001_initial'),
        ('warehouse', '0004_location_address_line1_location_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuptask',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='destination_location',
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_from', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tasktype'),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_to', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='putawaytask',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='putaway_from', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='putawaytask',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='putawaytask',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='putawaytask',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tasktype'),
        ),
        migrations.AddField(
            model_name='putawaytask',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='putaway_to', to='warehouse.location'),
        ),
        migrations.AlterField(
            model_name='pickuptask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuptask',
            name='outward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_tasks', to='inventory.outward'),
        ),
        migrations.AlterField(
            model_name='putawaytask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='putawaytask',
            name='inward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='putaway_tasks', to='inventory.inward'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertaskstatus',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertaskstatus',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usertaskstatus',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertaskstatus',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tasktype'),
        ),
        migrations.AlterField(
            model_name='usertaskstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
