# Generated by Django 5.2.4 on 2025-07-31 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventoryprocesstype_remove_inventorylog_action_type_and_more'),
        ('tasks', '0002_remove_pickuptask_source_location_and_more'),
        ('warehouse', '0004_location_address_line1_location_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putawaytask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='inward',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='item',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='putawaytask',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='usertaskstatus',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='usertaskstatus',
            name='task_type',
        ),
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_from', to='warehouse.location')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tasktype')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_to', to='warehouse.location')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventorytransaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usertaskstatus',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.inventorytask'),
        ),
        migrations.DeleteModel(
            name='PickUpTask',
        ),
        migrations.DeleteModel(
            name='PutAwayTask',
        ),
    ]
